args:
  - --kubelet-preferred-address-types=InternalIP
  - --kubelet-use-node-status-port
  - --metric-resolution=15s

resources:
  requests:
    cpu: 50m
    memory: 100Mi
  limits:
    memory: 200Mi

replicas: 2

nodeSelector:
  role: infra
tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
    effect: NoSchedule
